version: '3'

services:
  project-ratings:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - teste-postgres-compose
    networks:
      - postgres-compose-network
    environment:
      - DATABASE_URL=postgresql://postgres:1234@teste-postgres-compose:15432/db_patient_ratings
    restart: always
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "luhsimioni@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge